### PR TITLE
fix possible resource leaks when using SQLite3 database

### PR DESCRIPTION
**Pull request by striezel**
Database objects have to be deallocated in cases where queries fail, too, not just on the "happy path".

But that is not all. Connection objects are also allocated when one might not expect it. The [SQLite3 documentation on opening databases](https://sqlite.org/c3ref/open.html) also says:

> A [database connection](https://sqlite.org/c3ref/sqlite3.html) handle is usually returned in *ppDb, _**even if an error occurs.**_ The only exception is that if SQLite is unable to allocate memory to hold the [sqlite3](https://sqlite.org/c3ref/sqlite3.html) object, a NULL will be written into *ppDb instead of a pointer to the [sqlite3](https://sqlite.org/c3ref/sqlite3.html) object.

_(Emphasis is not part of the original documentation but was added by me.)_

So even if opening the database fails, an object might have been allocated. Thus, it needs to be deallocated, too.

Furthermore, prepared statement objects also need to be deallocated when the functions return earlier due to errors. So I fixed that, too. Let's hope that fixes all the leaks here.

### CODE REVIEW

**Comment by BonneCW** [comment]
Nice finding. Probably no big problem in Spine, but better to have it solved now than to run into issues later on.

**Comment by striezel** [comment]
> Probably no big problem in Spine [...]

Well, I did not check which of these methods are actually in use by Spine, but since the code is in the repository, I assumed that they are used somewhere.

> [...] but better to have it solved now than to run into issues later on.

I agree.
So is there anything left to do here or can the fix be merged?

**Comment by striezel** [comment]
@BonneCW: 
> So is there anything left to do here or can the fix be merged?

**Comment by striezel** [comment]
@BonneCW: I rebased those changes against the current `develop` branch.

**Comment by striezel** [comment]
@BonneCW: Looks like this is not exactly a top priority, but is there still a chance to get these changes merged? It's been more than half a year now, so I'd like to finish this.

**Pull request merged**
